### ISSUE TITLE
Images are not displayed right in safari

### ISSUE THREAD

**Issue by BorntraegerMarc** [NeilujD/paper-avatar#2]
Hi there

When viewing images in safari or generally iOS/mac devices then the images are off. Did anybody experience the same thing?

**Comment by BorntraegerMarc** [comment]
@NeilujD Does it get displayed correctly for you?

**Comment by BorntraegerMarc** [comment]
![image](https://cloud.githubusercontent.com/assets/7549295/23618860/0e698c7e-0292-11e7-89db-0c170d6fa655.png)

Here is an example using Safari on OSX on the webcomponents site example

**Comment by NeilujD** [comment]
Hi @BorntraegerMarc, thanks for reporting the issue.
It will be fixed in 2.0.1.
